Separate job for package tests

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -32,18 +32,37 @@ env:
 jobs:
 
   python-package:
-    name: Build and test Python package
+    strategy:
+      matrix:
+        python-version: [ '3.x', 'pypy-3.7' ]
+    name: Build and test Python package in ${{ matrix.python-version }} 
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - name: Force locale to UTF-8
+        run: |
+          apt-get update 
+          apt-get install -yq locales locales-all
+          apt-get clean
+          export LC_ALL=en_US.UTF-8
+          export LANG=en_US.UTF-8
+          export LANGUAGE=en_US.UTF-8
       - name: Set up Python 3.7
         uses: actions/setup-python@v2
         with:
-          python-version: '3.7'
-      - name: Install tox
-        run: python -m pip install -q tox
-      - name: Run tox tests
-        run: tox -- 
+          python-version: ${{ matrix.python-version }}
+          architecture: x64
+      - name: Install pytest
+        run: python -m pip install -q pytest
+      - name: Build sdist
+        run: |
+          echo ${LC_ALL}
+          python setup.py sdist -q
+          # [ ! -f dist/reactors-*.tar.gz ] && echo "could not find sdist" && exit 1
+      - name: Install sdist
+        run: python3 -m pip install -q dist/reactors-*.tar.gz 
+      - name: Run pytests
+        run: python3 -m pytest tests/test_000_imports.py
 
   docker-image:
     name: Build, test, and push Docker image 
@@ -51,7 +70,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       
-      # install dependencies
+      # Install dependencies
       - uses: actions/checkout@v2
       - name: Set up Python 3.7
         uses: actions/setup-python@v2
@@ -62,7 +81,7 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      # build
+      # Build
       - name: Build Docker image
         uses: docker/build-push-action@v2
         with:
@@ -72,7 +91,7 @@ jobs:
           push: false
           tags: ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
 
-      # test 
+      # Test 
       - name: Authenticate Tapis client
         run: |
           touch ~/.tapis_firstrun
@@ -88,7 +107,7 @@ jobs:
             -e _abaco_api_server=${TAPIS_BASE_URL} \
             ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
 
-      # push
+      # Push
       - name: Login to DockerHub
         if: github.event_name != 'pull_request'
         uses: docker/login-action@v1 
